<?php

/**
 * @file
 * Override the Wilson content editing experience.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view_alter().
 */
function wilson_content_entity_view_alter(&$build, EntityInterface $entity, $display) {
  // Override the map zoom display settings with the value of field_map_zoom.
  if ($entity->hasField('field_map_address') && $entity->hasField('field_map_zoom')) {
    $zoom = $entity->get('field_map_zoom')->getString();
    $build['field_map_address'][0]['#zoom'] = $zoom;
  }
}
